"""Comprehensive migration: fix messages, categories description, etc.

Revision ID: 0a617914ae88
Revises: 727862e0dfd9
Create Date: 2025-12-17 21:15:12.430701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a617914ae88'
down_revision: Union[str, Sequence[str], None] = '727862e0dfd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
